/**
 * Shared Godot project generators: project.godot + minimal .tscn factories.
 *
 * DESIGN DECISION (mínimo de erros): generated projects use "code-first
 * scenes" — each .tscn contains ONLY a root node + script; visuals, collision
 * and children are built in _ready() via GDScript. Scene files are the #1
 * source of generation errors; this architecture makes every artifact
 * individually parse-checkable by `godot --headless --check-only`.
 */
import type { GameSpec } from "../types";

export function projectGodot(spec: GameSpec): string {
  return `; Engine configuration file (generated by Nexus Forge)
config_version=5

[application]

config/name="${spec.title.replace(/"/g, "'")}"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.3")

[autoload]

GameState="*res://scripts/game_state.gd"
GameMenu="*res://scripts/game_menu.gd"

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="canvas_items"
window/stretch/aspect="keep"

[rendering]

renderer/rendering_method="gl_compatibility"
`;
}

export function godotIgnore(): string {
  return `# Godot 4+ specific ignores
.godot/
/android/
*.translation
export.cfg
`;
}

/** Minimal root-node scene with an attached script (format=3, Godot 4). */
export function rootScene(nodeName: string, nodeType: string, scriptPath: string): string {
  return `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="${scriptPath}" id="1_root"]

[node name="${nodeName}" type="${nodeType}"]
script = ExtResource("1_root")
`;
}

export function iconSvg(color: string, accent: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128">
<rect width="128" height="128" rx="16" fill="${color}"/>
<path d="M64 22 L106 64 L64 106 L22 64 Z" fill="none" stroke="${accent}" stroke-width="8" stroke-linejoin="round"/>
<circle cx="64" cy="64" r="12" fill="${accent}"/>
</svg>
`;
}

/** Shared HUD script (CanvasLayer with live labels) used by 2D templates. */
export function hudScript(spec: GameSpec): string {
  return `extends CanvasLayer
# HUD built in code — no scene assets required.
# Shows title, objective, vitals and the world clock (colony feel).

var title_label: Label
var status_label: Label
var clock_label: Label
var message_label: Label

func _ready() -> void:
	add_to_group("hud")
	title_label = Label.new()
	title_label.text = "${spec.title.replace(/"/g, "'")}"
	title_label.position = Vector2(16, 10)
	title_label.add_theme_font_size_override("font_size", 22)
	title_label.add_theme_color_override("font_color", Color("${spec.palette.fg}"))
	add_child(title_label)

	status_label = Label.new()
	status_label.position = Vector2(16, 40)
	status_label.add_theme_font_size_override("font_size", 15)
	status_label.add_theme_color_override("font_color", Color("${spec.palette.fg}"))
	add_child(status_label)

	clock_label = Label.new()
	clock_label.position = Vector2(16, 64)
	clock_label.add_theme_font_size_override("font_size", 13)
	clock_label.add_theme_color_override("font_color", Color("${spec.palette.accent}"))
	add_child(clock_label)

	message_label = Label.new()
	message_label.position = Vector2(340, 300)
	message_label.size = Vector2(600, 120)
	message_label.add_theme_font_size_override("font_size", 34)
	message_label.add_theme_color_override("font_color", Color("${spec.palette.accent}"))
	message_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	message_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	add_child(message_label)
	message_label.text = ""

func show_message(text: String) -> void:
	message_label.text = text

func _process(_delta: float) -> void:
	if GameState == null:
		return
	status_label.text = "Objective: collect %d shards   |   Integrity: %d%%" % [max(GameState.goal - GameState.score, 0), GameState.health]
	clock_label.text = "Cycle %s" % GameState.clock_text()
`;
}
