/**
 * Release builder — turns the whole studio into standalone executables:
 *   nexus-forge.exe (Windows x64) · nexus-forge (Linux x64) · nexus-forge-macos
 *
 * Steps: build UI → embed it as base64 → bun --compile per target.
 * Bun's standalone executables embed the runtime, so users just double-click.
 */
import { readdirSync, readFileSync, statSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, relative } from "node:path";
import { execSync } from "node:child_process";

const ROOT = join(import.meta.dir, "..");
const UI_DIST = join(ROOT, "apps", "ui", "dist");
const EMBED_TS = join(ROOT, "packages", "core", "src", "ui-embed.generated.ts");
const OUT_DIR = join(ROOT, "dist-release");
mkdirSync(OUT_DIR, { recursive: true });

// 1) embed UI
const files: Record<string, string> = {};
function walk(dir: string) {
  for (const f of readdirSync(dir)) {
    const abs = join(dir, f);
    if (statSync(abs).isDirectory()) walk(abs);
    else files[relative(UI_DIST, abs)] = readFileSync(abs).toString("base64");
  }
}
if (existsSync(join(UI_DIST, "index.html"))) {
  walk(UI_DIST);
  const body = Object.entries(files).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n");
  writeFileSync(EMBED_TS, `/** AUTO-GENERATED by scripts/build-release.ts — the entire UI, embedded. */\nexport const UI_EMBED: Record<string, string> = {\n${body}\n};\n`);
  console.log(`· UI embedded: ${Object.keys(files).length} files`);
} else {
  console.error("✖ UI not built — run `pnpm ui:build` first.");
  process.exit(1);
}

// 2) compile per target
const TARGETS: Array<[string, string, string]> = [
  ["bun-windows-x64", "nexus-forge.exe", "Windows x64"],
  ["bun-linux-x64", "nexus-forge", "Linux x64"],
  ["bun-darwin-arm64", "nexus-forge-macos", "macOS Apple Silicon"],
];

for (const [target, out, label] of TARGETS) {
  console.log(`· compiling ${label}…`);
  execSync(
    `bun build --compile --target=${target} --outfile "${join(OUT_DIR, out)}" packages/core/src/main.ts`,
    { cwd: ROOT, stdio: "inherit" },
  );
}

console.log(`\n✓ Standalone builds in ${OUT_DIR}:`);
for (const [, out] of TARGETS) {
  const p = join(OUT_DIR, out);
  if (existsSync(p)) console.log(`  ${out}  (${(statSync(p).size / 1048576).toFixed(1)} MB)`);
}
console.log(`\nUsage: run the executable — it starts the studio and opens http://127.0.0.1:5180 in your browser.`);
